class SceneOne extends Phaser.Scene {

    constructor() {
        super({ key: 'SceneOne' });
        this.player = null;      // To hold the player object
        this.groundGroup = null; // To hold the ground tiles
        this.wallGroup = null;   // Group for the wall tiles
        this.gameState = 'pending'; // Add game state: pending, animating, tax_intro, playing
        this.startButton = null;   // To hold the start button text object
        this.infoText = null;      // Text like "You made 3 million dollars!"
        this.funnel = null;        // Funnel sprite
        this.coinEmitter = null;   // Particle emitter for coins
        this.counterText = null;   // Text for the dollar amount
        this.counterValue = { value: 0 }; // Object to tween for dollars
        this.ethCounterText = null;     // Text for the ETH amount
        this.ethCounterValue = { value: 0 }; // Object to tween for ETH
        this.aaveCounterText = null;    // Text for the Aave loan amount
        this.aaveCounterValue = { value: 0 }; // Value for Aave loan
        this.warningText = null;   // Text for "here comes the tax monster!"
        this.taxMonster = null;    // Tax monster sprite
        this.enemyManager = null;  // To hold the EnemyManager instance
        this.groundTileSize = 64;  // Store tile size for reuse
        this.spikeWallXPosition = 4800; // Approx. X position for the new spike wall (tile 75 * 64)
        this.isTaxMonsterStopped = false; // Flag for monster state
        this.questionMarkBlock = null;    // To hold the question mark block sprite
        this.isQuestionMarkBlockHit = false; // Flag for question mark block hit
        this.aaveLoanObject = null; // To hold the Aave loan placeholder object
        this.isWallDestroyed = false; // Flag for wall destruction state
        this.agentSpawningStopped = false; // Flag to check if agent spawning is stopped
        this.bgFar = null;         // Reference to the far background TileSprite
        this.bgMid = null;         // Reference to the mid background TileSprite
        this.bgClose = null;       // Reference to the close background TileSprite
        this.sceneTransitioned = false; // Flag to prevent multiple scene transitions

        // --- Spike Wall Collider Tuning ---
        this.SPIKE_WALL_BODY_WIDTH_MULT   = 0.8; // fraction (0–1) of frame width
        this.SPIKE_WALL_BODY_HEIGHT_MULT  = 0.8; // fraction (0–1) of frame height
        this.SPIKE_WALL_VERTICAL_ADJUST   = 2;   // +ve moves collider up, –ve down (un-scaled px)
        this.SPIKE_WALL_HORIZ_ADJUST      = 30; // +ve ⇒ shift collider right, –ve ⇒ left (scaled px)
        this.SPIKE_WALL_SPRITE_DOWN_ADJUST = 50;  // pixels to nudge the *sprite* downward after snap
        // ------------------------------------
    }

    preload() {
        console.log("SceneOne: preload");
        // Textures should already be loaded/generated by BootScene
    }

    create(data) {
        // --- Initialize music ---
        // const bootScene = this.scene.get('BootScene'); // Not needed this way
        const musicManager = this.registry.get('musicManager');
        if (musicManager) {
            musicManager.play('sceneOneMusic', { loop: true, volume: 0.4 });
            console.log("SceneOne: Attempting to play 'sceneOneMusic'.");
        } else {
            console.warn('SceneOne: MusicManager not found in registry. Cannot play music.');
        }
        // --- End music initialization ---

        console.log("SceneOne: create", data);
        // this.gameState = 'pending'; // gameState will be set by the sequence
        // this.counterValue.value = 0; // Reset dollar counter - Now set by data
        // this.ethCounterValue.value = 0; // Reset ETH counter - Now set by data

        // --- Initialize counters from passed data ---
        if (data && data.dollars !== undefined) {
            this.counterValue.value = data.dollars;
        }
        if (data && data.eth !== undefined) {
            this.ethCounterValue.value = data.eth;
        }

        // --- Basic Scene Setup ---
        this.cameras.main.setBackgroundColor('#add8e6'); // Light blue background
        const gameWidth = this.scale.width;
        const gameHeight = this.scale.height;

        // --- Calculate world width based on ground tiles ---
        const numGroundTiles = 500; // Ensure this matches ground creation logic
        const groundTileSize = 64;  // Ensure this matches ground creation logic
        const worldWidth = numGroundTiles * groundTileSize;

        // --- Add Parallax Backgrounds (single wide images) ---
        this.bgFar = this.add.image(0, 0, 'scene1_bg_far')
            .setOrigin(0, 0)
            .setDepth(-10)
            .setScrollFactor(0.2);
        this.bgMid = this.add.image(0, 0, 'scene1_bg_mid')
            .setOrigin(0, 0)
            .setDepth(-9)
            .setScrollFactor(0.5);
        // NEW: Close / near layer for extra parallax depth
        this.bgClose = this.add.image(0, 0, 'scene1_bg_close')
            .setOrigin(0, 0)
            .setDepth(-8)
            .setScrollFactor(0.8);

        this.groundTileSize = 64; // Ensure ground tile size is set
        // REMOVED: const numGroundTiles = 500; // Moved calculation earlier
        // REMOVED: const worldWidth = numGroundTiles * this.groundTileSize; // Moved calculation earlier
        // Match world height to the actual canvas height so physics bodies and ground align
        const worldHeight = gameHeight;
        // Set initial full world bounds (will be restricted in update until 'playing')
        this.physics.world.setBounds(0, 0, worldWidth, worldHeight);

        // --- Create Ground ---
        this.groundGroup = this.physics.add.staticGroup();
        const groundY = gameHeight - this.groundTileSize / 2;
        console.log(`Creating ${numGroundTiles} fixed ground tiles at Y=${groundY}.`);

        const groundFrames = ['ground1.png', 'ground2.png', 'ground3.png']; // Frames from your new atlas

        for (let i = 0; i < numGroundTiles; i++) {
            const x = i * this.groundTileSize + this.groundTileSize / 2; // Center ground tiles

            // Create the tile (initially still uses placeholder just to establish object, or could be null texture)
            const tile = this.groundGroup.create(x, groundY, 'ground-placeholder');
            tile.setOrigin(0.5);

            // Randomly select one of the new ground frames
            const randomFrameName = Phaser.Math.RND.pick(groundFrames);
            tile.setTexture('ground_atlas', randomFrameName); // Use the new ground_atlas

            // Scale the visual to fit the 64x64 tile size
            tile.setDisplaySize(this.groundTileSize, this.groundTileSize);
            
            // Refresh the static body to match the new texture an_d display size (should be 64x64)
            tile.refreshBody();

            // --- Snap tile visuals to the ground line ---
            // Calculate how far the visual bottom of the scaled tile is from the intended groundY
            // Note: tile.y is its center, tile.displayHeight is 64. So, visual bottom *should* be tile.y + 32.
            // groundY is also the center of the physics body. The bottom of the physics body is groundY + this.groundTileSize / 2)
            const visualBottom = tile.getBounds().bottom;
            const physicsBottom = groundY + (this.groundTileSize / 2);
            const delta = physicsBottom - visualBottom;

            if (Math.abs(delta) > 0.1) { // Use a small tolerance for floating point issues
                tile.y += delta;
                // The physics body's position is absolute, so we don't need to refresh it again if only 'y' of sprite changes,
                // as the physics body was already created at the correct groundY.
                // However, if we were changing the body's *size* or *shape*, refreshBody() would be needed.
                // For static bodies, their position is fixed when created. Adjusting sprite 'y' moves the visual.
            }

            // Add debug number if debug is enabled
            if (this.physics.config.debug) {
                this.add.text(x, groundY - this.groundTileSize / 2, i.toString(), {
                    fontSize: '12px', fill: '#fff', backgroundColor: '#000'
                }).setOrigin(0.5).setName(`debug_text_${i}`);
            }
        }

        // --- Create Spike Wall Obstacle ---
        this.spikeWall = this.physics.add.staticImage(this.spikeWallXPosition, groundY, 'wall-tree-spikes_atlas', 'wall-tree-spikes.png');
        
        // The atlas frame is "wall-tree-spikes.png"
        // Adjust origin to bottom-center so we can place it flush on the ground.
        this.spikeWall.setOrigin(0.5, 1);

        // --- Scale sprite so it touches the top of the view ---
        const desiredVisualHeight = groundY;  // ground → top of canvas
        const wallScale = desiredVisualHeight / this.spikeWall.height;
        this.spikeWall.setScale(wallScale);

        // --- Now size the body in *scaled* pixels so refreshBody() isn't needed ---
        const bodyWScaled = this.spikeWall.displayWidth  * Math.max(0.01, Math.min(Math.abs(this.SPIKE_WALL_BODY_WIDTH_MULT), 1));
        const bodyHScaled = this.spikeWall.displayHeight * Math.max(0.01, Math.min(Math.abs(this.SPIKE_WALL_BODY_HEIGHT_MULT), 1));

        this.spikeWall.body.setSize(bodyWScaled, bodyHScaled);

        const offsetXScaled = (this.spikeWall.displayWidth  - bodyWScaled) / 2 + this.SPIKE_WALL_HORIZ_ADJUST;
        const offsetYScaled = (this.spikeWall.displayHeight - bodyHScaled) - (this.SPIKE_WALL_VERTICAL_ADJUST * wallScale);

        this.spikeWall.body.setOffset(offsetXScaled, offsetYScaled);

        console.log(`Created spike wall at X=${this.spikeWallXPosition}, Y=${groundY}, Scale=${wallScale.toFixed(2)}`);
        console.log(`Spike wall display size (scaled): ${this.spikeWall.displayWidth.toFixed(1)}x${this.spikeWall.displayHeight.toFixed(1)}`);
        console.log(`Spike wall physics body size (scaled): ${this.spikeWall.body.width.toFixed(1)}x${this.spikeWall.body.height.toFixed(1)}`);
        console.log(`Body offset (scaled): ${offsetXScaled.toFixed(1)}, ${offsetYScaled.toFixed(1)}`);

        // --- Snap sprite so its *visible* bottom touches the ground exactly (accounts for trimming) ---
        const spriteBottom = this.spikeWall.getBounds().bottom;
        const deltaToGround = groundY - spriteBottom;
        if (Math.abs(deltaToGround) > 0.5) { // Only adjust if not already aligned
            this.spikeWall.y += deltaToGround;
            this.spikeWall.body?.reset(this.spikeWall.x, this.spikeWall.y);
        }

        // --- Optional manual nudge to make vines visually touch ground ---
        if (this.SPIKE_WALL_SPRITE_DOWN_ADJUST !== 0) {
            this.spikeWall.y += this.SPIKE_WALL_SPRITE_DOWN_ADJUST;
            this.spikeWall.body?.reset(this.spikeWall.x, this.spikeWall.y);
        }
        // End bottom-edge snap

        // --- Create Player ---
        // Create player first (origin is default 0.5, 0.5)
        const playerStartX = gameWidth / 2;
        this.player = new Player(this, playerStartX, 0); // Temp Y=0
        // Calculate Y to place the player's center relative to ground top
        const groundTopY = gameHeight - this.groundTileSize;
        const playerHalfHeight = this.player.displayHeight / 2;
        const buffer = 25; // Increased buffer from 5 to 25 pixels
        const playerStartY = groundTopY - playerHalfHeight - buffer; // Place higher above ground
        this.player.setY(playerStartY); // Set the slightly elevated Y position
        this.player.setCollideWorldBounds(true); // Collide with world bounds from the start
        console.log(`Player intentionally positioned slightly high at Y: ${playerStartY}. Expect physics to settle it.`);

        // --- Physics Collisions ---
        this.physics.add.collider(this.player, this.groundGroup);
        this.physics.add.collider(this.player, this.spikeWall, this.handlePlayerWallCollision, null, this); // NEW SPIKE WALL
        console.log("Colliders set between player and ground/spike wall.");

        // --- Create Enemy Manager --- 
        this.enemyManager = new EnemyManager(this);
        console.log("Enemy Manager created.");

        // Add collider between player and agents using the manager's group
        this.physics.add.collider(this.player, this.enemyManager.getGroup(), this.handlePlayerAgentCollision, null, this);
        // *** ADD COLLIDER: Agents vs Ground ***
        this.physics.add.collider(this.enemyManager.getGroup(), this.groundGroup);

        // --- Camera Setup (Initial) ---
        // Keep camera fixed initially, looking at the start area
        this.cameras.main.setBounds(0, 0, worldWidth, worldHeight);
        // DO NOT start follow yet

        // --- Counter Text (Pinned to Top-Left) ---
        this.counterText = this.add.text(20, 20, '$: 0', { // Use $ symbol, position at (20, 20)
            fontSize: '24px', fill: '#fff', stroke: '#000', strokeThickness: 4 // Changed fill to white, added stroke
        }).setOrigin(0, 0)
          .setScrollFactor(0); // Pin it

        // --- ETH Counter Text (Below Dollar Counter) ---
        this.ethCounterText = this.add.text(20, 50, 'ETH: 0', { // Position below at (20, 50)
            fontSize: '24px', fill: '#fff', stroke: '#000', strokeThickness: 4 // Changed fill to white, added stroke
        }).setOrigin(0, 0)
            .setScrollFactor(0); // Pin it

        // --- Aave Counter Text (Below ETH Counter, Initially Hidden) ---
        this.aaveCounterText = this.add.text(20, 80, 'Aave: 0', { // Position below ETH at (20, 80)
            fontSize: '24px', fill: '#ADD8E6', stroke: '#000', strokeThickness: 4 // Use light blue, added stroke
        }).setOrigin(0, 0)
            .setScrollFactor(0) // Pin it
            .setVisible(false); // Start hidden

        // --- Update counter display with initial values ---
        this.counterText.setText(`$: ${Math.floor(this.counterValue.value).toLocaleString()}`);
        this.ethCounterText.setText(`ETH: ${Math.floor(this.ethCounterValue.value)}`);

        // --- Initial Player Constraints ---
        // REMOVED: this.physics.world.setBounds(0, 0, gameWidth, worldHeight);
        // Bounds are now handled dynamically in update until 'playing'

        // --- Create Tax Monster --- // MOVED to endAnimationSequence
        /*
        const monsterPlaceholderWidth = 160; // Keep for positioning logic reference
        const monsterPlaceholderHeight = 320;
        const monsterStartX = -monsterPlaceholderWidth; // Start off-screen left
        const monsterStartY = worldHeight - this.groundTileSize - monsterPlaceholderHeight / 2; // Position based on placeholder dims
        
        // Use the Enemy class
        this.taxMonster = new Enemy(this, monsterStartX, monsterStartY, 'tax-monster_atlas');
        
        // Set properties not handled by default Enemy constructor or should be scene-specific
        // this.taxMonster.body.setAllowGravity(false); // Enemy class doesn't set gravity by default
        this.taxMonster.setImmovable(true); // Keep this behaviour
        this.taxMonster.setDepth(5); // Ensure consistent depth

        // Enemy class constructor logs creation
        // console.log("GameScene: Tax Monster created at", monsterStartX, monsterStartY);
        */

        console.log("SceneOne setup complete. Initializing tax monster sequence.");

        // --- Directly start the sequence that was previously endAnimationSequence ---
        // This will set the gameState to 'tax_intro' and handle the monster
        this.introduceTaxMonster(); 
    }

    // RENAMED and REFACTORED: This was startAnimationSequence, now it's effectively skipped
    // The "3 million dollars" part is moved to ThreeMillionScene.
    // This scene now directly proceeds to tax monster intro via introduceTaxMonster()
    /* 
    startAnimationSequence() {
        // ... THIS WHOLE METHOD'S ORIGINAL CONTENT IS MOVED OR OBSOLETE ...
    }
    */

    // RENAMED and REFACTORED: This was endAnimationSequence
    // It's now the main sequence that starts when SceneOne is entered.
    introduceTaxMonster() {
        console.log("SceneOne: Starting tax monster intro sequence...");
        // if (this.gameState !== 'animating') return; // This check is no longer relevant here

        // Clean up elements from ThreeMillionScene (they are not in this scene anymore)
        // if (this.infoText) this.infoText.destroy(); // MOVED
        // if (this.funnel) this.funnel.destroy(); // MOVED
        // if (this.coinEmitter) this.coinEmitter.destroy(); // MOVED
        // Counter text remains and is managed by this scene

        // Start Tax Monster Sequence
        this.gameState = 'tax_intro'; // New state for this sequence

        // Immediately shake the screen and spawn the Tax Monster (no warning text or delay)
        this.cameras.main.shake(500, 0.02);

        // --- Spawn Tax Monster (off-screen left) ---
        const currentGroundTopY = this.scale.height - this.groundTileSize;

        // Spawn off-screen left; Y will be corrected after we know its real display height.
        const monsterStartX = -160; // arbitrary off-screen value; X corrected by tween later
        const monsterTempY  = 0;    // placeholder Y

        // Spawn Enemy without custom body so it auto-sizes.
        this.taxMonster = new Enemy(this, monsterStartX, monsterTempY, 'tax-monster_atlas');

        // Now that we know the scaled display height, place its bottom exactly on the ground.
        const monsterDisplayH = this.taxMonster.displayHeight;      // already includes scale
        const monsterStartY   = currentGroundTopY - monsterDisplayH / 2;
        this.taxMonster.setY(monsterStartY);
        // Make sure the physics body is synced with the new position
        this.taxMonster.body?.reset(this.taxMonster.x, monsterStartY);

        // Pixel-perfect snap using the physics body bottom
        const bodyBottom = this.taxMonster.body?.bottom ?? this.taxMonster.getBounds().bottom;
        const deltaY = currentGroundTopY - bodyBottom;
        if (deltaY !== 0) {
            this.taxMonster.y += deltaY;
            this.taxMonster.body?.reset(this.taxMonster.x, this.taxMonster.y);
        }

        // Extra snap using sprite bounds (accounts for trimmed frame)
        const spriteBottom = this.taxMonster.getBounds().bottom;
        const deltaSprite  = currentGroundTopY - spriteBottom;
        if (deltaSprite !== 0) {
            this.taxMonster.y += deltaSprite;
            this.taxMonster.body?.reset(this.taxMonster.x, this.taxMonster.y);
        }

        // Collider with Player (ensure it's added once)
        this.physics.add.collider(this.player, this.taxMonster, this.handlePlayerMonsterCollision, null, this);

        // --- Tween Monster onto Screen ---
        this.tweens.add({
            targets: this.taxMonster,
            x: 160,
            duration: 1500,
            ease: 'Power2',
            onStart: () => {
                // Play monster entrance sound when tween begins
                const soundManager = this.registry.get('soundManager');
                if (soundManager) {
                    soundManager.playSound('monsterEntranceSound', { volume: 0.1 });
                } else {
                    console.warn('SceneOne: SoundManager not found. Cannot play monster entrance sound.');
                }
            },
            onComplete: () => {
                console.log("Tax monster arrived. Game state changing to playing.");
                // Transition to Playing State AFTER monster arrives
                this.gameState = 'playing';
                this.cameras.main.startFollow(this.player, true, 0.1, 0.1);
                // Ensure world bounds are fully expanded for playing state
                this.physics.world.setBounds(0, 0, this.physics.world.bounds.width, this.physics.world.bounds.height);

                // --- Start Spawning Agents via Manager ---
                this.enemyManager.startSpawningAgents();

                // Allow the monster to push the player after arriving
                this.taxMonster.setImmovable(false);
                this.taxMonster.body.setMass(1000); // Make monster heavy so it pushes player
                this.taxMonster.setDepth(5);
            }
        });
    }

    handlePlayerMonsterCollision(player, monster) {
        console.log("COLLISION WITH TAX MONSTER!");
        // REMOVED: this.scene.restart(); 
        // Now the monster just acts as a physical barrier
    }

    handlePlayerAgentCollision(player, agent) {
        console.log("COLLISION WITH IRS AGENT! Losing dollars.");
        
        // --- Play Player Ow Sound ---
        const soundManager = this.registry.get('soundManager');
        if (soundManager) {
            const owSound = soundManager.playSound('playerOwSound', { volume: 0.2 });
            if (owSound && owSound.once) {
                owSound.once('complete', () => {
                    soundManager.playSound('ringlossSound', { volume: 0.25 });
                });
            } else {
                // Fallback: play second sound after short delay
                this.time.delayedCall(300, () => {
                    soundManager.playSound('ringlossSound', { volume: 0.25 });
                });
            }
        } else {
            console.warn('SceneOne: SoundManager not found. Cannot play player ow / ringloss sounds.');
        }
        // --- End Sound ---
        
        // --- NEW: Player Hit Effects ---
        // Prevent effect stacking if already hit
        if (player.isHit) return; // Stop if already processing a hit

        // Camera Shake
        this.cameras.main.shake(120, 0.008);

        // Tint player red temporarily
        player.isHit = true;        // Set the flag
        // Increment global hit counter
        this.registry.set('playerHits', (this.registry.get('playerHits') || 0) + 1);
        player.setTint(0xff0000);
        this.time.delayedCall(400, () => {
            player.clearTint();
            player.isHit = false; // Clear the flag after delay
        }, [], this);
        // --- END NEW ---

        // Maybe knock player back slightly or just restart for now
        // REMOVED: this.scene.restart();

        // 1. Subtract Dollars
        const dollarsToLose = 100000;
        this.counterValue.value = Math.max(0, this.counterValue.value - dollarsToLose); // Don't go below 0
        this.counterText.setText(`$: ${Math.floor(this.counterValue.value).toLocaleString()}`); // Update text with $ format
        // ETH is not affected by this collision

        // 2. Create Coin Burst Effect at Player Position using sprites
        this.spawnCoinBurst(player.x, player.y, player.depth + 1);

        // 3. Destroy the specific agent that was hit
        agent.destroy();

        // Optional: Add brief invincibility or knockback later
        // player.setAlpha(0.5);
        // this.time.delayedCall(500, () => { player.setAlpha(1.0); });
    }

    spawnCoinBurst(x, y, depth) {
        const count = Phaser.Math.Between(10, 20);
        for (let i = 0; i < count; i++) {
            // Use real coin art loaded via BootScene (single-frame atlas)
            const coin = this.physics.add.image(x, y, 'coin_atlas', 'coin.png');

            // Match ThreeMillionScene technique: use un-scaled frame width
            const unscaledCoinWidth = coin.frame.width;
            const desiredDisplayWidth = 64; // ≈ one ground tile
            const scaleFactor = desiredDisplayWidth / unscaledCoinWidth;
            coin.setScale(scaleFactor);

            coin.setDepth(depth);

            // Set a circular physics body based on UN-SCALED width so scale is applied automatically
            if (coin.body && coin.body.setCircle) {
                coin.body.setCircle(unscaledCoinWidth / 2);
            }

            // Random burst trajectory
            const angle = Phaser.Math.FloatBetween(0, Math.PI * 2);
            const speed = Phaser.Math.Between(150, 300);
            coin.setVelocity(Math.cos(angle) * speed, Math.sin(angle) * speed - 150);
            coin.setGravityY(800);

            // Enable collision with the ground so coins land and bounce
            this.physics.add.collider(coin, this.groundGroup);

            // Make them bounce a little for visual flair
            coin.setBounce(0.3);

            // Optional: clean-up after a few seconds to avoid piling up forever
            this.time.delayedCall(5000, () => {
                if (coin && coin.active) {
                    coin.destroy();
                }
            });
        }
    }

    handlePlayerWallCollision(player, wallObject) {
        // Only trigger if the loan has been acquired and the wall isn't already destroyed
        if (this.aaveLoanObject && this.isQuestionMarkBlockHit && !this.isWallDestroyed) {
            console.log("Player with Aave loan hit the spike wall!");
            this.isWallDestroyed = true; // Prevent multiple triggers

            // --- Play Barrier Success Sound ---
            const soundManager = this.registry.get('soundManager');
            if (soundManager) {
                soundManager.playSound('barrierSuccessSound', { volume: 0.1 });
            } else {
                console.warn('SceneOne: SoundManager not found. Cannot play barrier success sound.');
            }
            // --- End Sound ---

            // 1. Destroy the Aave loan object (maybe add a tween later)
            if (this.aaveLoanObject) {
                this.aaveLoanObject.destroy();
                this.aaveLoanObject = null;
            }

            // 2. Immediately disable wall physics so player can pass through
            if (wallObject === this.spikeWall && this.spikeWall.body) {
                this.spikeWall.disableBody(true, false); // Disable physics but keep visible for fade
            }

            // 3. Create a fade-out tween for the spike wall
            this.tweens.add({
                targets: this.spikeWall, // Target the single spikeWall sprite
                alpha: 0, // Fade to transparent
                duration: 500, // Fade duration in ms
                ease: 'Linear',
                onComplete: () => {
                    // 4. Destroy the wall sprite completely after fading
                    if (this.spikeWall) {
                        this.spikeWall.destroy();
                        this.spikeWall = null;
                    }
                    console.log("Spike Wall faded and destroyed. Transitioning to InterstitialScene for SceneTwo.");

                    // --- Fade out music before transitioning ---
                    const musicManager = this.registry.get('musicManager');
                    if (musicManager) {
                        musicManager.fadeOutCurrentTrack(800); // 800ms fade
                    }
                    // --- End music fade out ---

                    // Play.fun: level 1 complete bonus
                    awardPoints(100);

                    // --- Start Next Scene via Interstitial (Pass Counter Data) ---
                    const counterData = {
                        dollars: this.counterValue.value,
                        eth: this.ethCounterValue.value,
                        aave: this.aaveCounterValue.value,
                        hits: this.registry.get('playerHits')
                    };
                    // Transition to the Interstitial Scene first
                    this.scene.start('InterstitialScene', {
                        nextSceneKey: 'SceneTwo',
                        imageKey: 'interstitial2',
                        sceneData: counterData
                    });
                    // this.scene.start('SceneTwo', counterData); // Old direct transition
                }
            });
        }
        // If conditions aren't met, the collision behaves normally (player stops)
    }

    update(time, delta) {
        if (this.player) {
            this.player.update(time, delta);
            // TEMP DEBUG: Show collider bottom vs ground line
            if (window.APPLY_BODY_DEBUG) {
                const groundTopY = this.physics.world.bounds.height - this.groundTileSize;
                console.log(`[Scene1Bottom] frame=${this.player.frame.name}` +
                    ` bottom=${this.player.body.bottom.toFixed(1)}` +
                    ` ground=${groundTopY.toFixed(1)}` +
                    ` diff=${(this.player.body.bottom - groundTopY).toFixed(1)}` +
                    ` onFloor=${this.player.body.onFloor()}`);
            }
        }

        // --- Update Tax Monster (if it exists) ---
        if (this.taxMonster) {
            this.taxMonster.update(time, delta);
        }
        // --- End Tax Monster Update ---

        // --- Update Enemy Manager --- 
        if (this.enemyManager) {
            this.enemyManager.update(time, delta);
        }

        // --- Game State Logic ---
        if (this.gameState === 'pending' || this.gameState === 'animating' || this.gameState === 'tax_intro') {
            // Restrict player movement to initial screen width during non-playing states
            if (this.player.x < this.player.width / 2) {
                 this.player.x = this.player.width / 2;
                 this.player.setVelocityX(0);
             }
            if (this.player.x > this.scale.width - this.player.width / 2) {
                 this.player.x = this.scale.width - this.player.width / 2;
                 this.player.setVelocityX(0);
             }
            // Ensure physics bounds match screen width during these states
            // REMOVED: this.physics.world.setBounds(0, 0, this.scale.width, this.physics.world.bounds.height);
            // The player position is clamped manually above. Bounds are set once when transitioning to 'playing'.

        } else if (this.gameState === 'playing') {
            // Allow full world movement - bounds are already set
            // REMOVED: Setting bounds again here
            // this.physics.world.setBounds(0, 0, this.physics.world.bounds.width, this.physics.world.bounds.height);
            // Camera follow is active

            // --- Stop Agent Spawning near Wall ---
            if (!this.agentSpawningStopped && this.enemyManager) {
                const stopSpawnX = this.spikeWallXPosition - (15 * this.groundTileSize); // Stop 15 tiles before the new spike wall
                if (this.player.x >= stopSpawnX) {
                    console.log("SceneOne: Player near wall, stopping agent spawns.");
                    this.enemyManager.stopSpawningAgents();
                    this.agentSpawningStopped = true;
                }
            }
            // --- End Stop Agent Spawning ---

            // --- Dollar Value Decrease Over Time (Linked to Monster Progress) ---
            if (this.taxMonster && !this.isTaxMonsterStopped) {
                const startValue = 3000000;
                const endValue = 2300000;
                const totalDecrease = startValue - endValue;

                const monsterStartX = 160; // Approx X position after tween onto screen
                const stopTileIndex = 70;
                const stopBuffer = 20;
                const monsterStopX = (stopTileIndex * this.groundTileSize) + (this.groundTileSize / 2) - (this.taxMonster.width / 2) - stopBuffer;
                const monsterTravelDistance = monsterStopX - monsterStartX;

                if (monsterTravelDistance > 0) { // Avoid division by zero
                    const currentMonsterTravel = Math.max(0, this.taxMonster.x - monsterStartX);
                    const progress = Phaser.Math.Clamp(currentMonsterTravel / monsterTravelDistance, 0, 1);
                    const currentDecrease = totalDecrease * progress;
                    const newCounterValue = startValue - currentDecrease;

                    // Update the counter value, ensuring it doesn't go below the target endValue during this phase
                    this.counterValue.value = Math.max(endValue, newCounterValue);
                    this.counterText.setText(`$: ${Math.floor(this.counterValue.value).toLocaleString()}`);
                }
            }
            // --- End Dollar Value Decrease ---

            // --- Tax Monster Movement & Stopping Logic ---
            if (this.taxMonster) { // Check if monster exists
                // --- Condition for Normal Monster Movement ---
                // Monster moves forward ONLY if the final sequence hasn't been triggered yet
                if (!this.isTaxMonsterStopped) {
                    const currentSpeed = this.taxMonster.body.velocity.x;
                    const maxSpeed = 300; // Increased from 120
                    const acceleration = 4; // Increased from 0.25

                    if (currentSpeed < maxSpeed) {
                        this.taxMonster.setVelocityX(Math.min(currentSpeed + acceleration, maxSpeed));
                    } else {
                        this.taxMonster.setVelocityX(maxSpeed);
                    }
                }

                // --- Condition to Trigger the Final Jump Sequence ---
                // Check if player reached trigger tile AND sequence hasn't started
                const playerTriggerStopTileIndex = 65;
                const playerNearStopArea = this.player.x > (playerTriggerStopTileIndex * this.groundTileSize);

                if (playerNearStopArea && !this.isTaxMonsterStopped) {
                    this.isTaxMonsterStopped = true; // Set flag IMMEDIATELY
                    console.log(`Player reached tile ${playerTriggerStopTileIndex}. Triggering monster jump sequence.`);

                    // Stop any existing horizontal movement before starting tweens
                    this.taxMonster.setVelocityX(0);
                    // Calculate target X position for the monster's landing
                    const stopTileIndex = 70;
                    const stopBuffer = 20;
                    const monsterStopX = (stopTileIndex * this.groundTileSize) + (this.groundTileSize / 2) - (this.taxMonster.width / 2) - stopBuffer;

                    // --- Monster Jump Sequence ---
                    // --- Play Monster Jump Sound ---
                    const soundManager = this.registry.get('soundManager');
                    if (soundManager) {
                        soundManager.playSound('monsterJumpSound', { volume: 0.2 });
                    } else {
                        console.warn('SceneOne: SoundManager not found. Cannot play monster jump sound.');
                    }
                    // --- End Sound ---

                    const jumpHeight = 100;
                    const jumpUpDuration = 300;
                    const jumpDownDuration = 250;
                    const totalJumpDuration = jumpUpDuration + jumpDownDuration;
                    const originalMonsterY = this.taxMonster.y; // Store starting Y
                    const startingMonsterX = this.taxMonster.x; // Store starting X

                    // 1. Tween X (Horizontal movement to stop point during the jump)
                    this.tweens.add({
                        targets: this.taxMonster,
                        x: monsterStopX,
                        duration: totalJumpDuration,
                        ease: 'Quad.easeInOut' // Smooth horizontal movement
                    });

                    // 2. Tween Y (Vertical Jump Up)
                    this.tweens.add({
                        targets: this.taxMonster,
                        y: originalMonsterY - jumpHeight,
                        duration: jumpUpDuration,
                        ease: 'Power2.easeOut',
                        onComplete: () => {
                            // 3. Tween Y (Vertical Jump Down - Landing)
                            this.tweens.add({
                                targets: this.taxMonster,
                                y: originalMonsterY, // Return to original Y
                                duration: jumpDownDuration,
                                ease: 'Bounce.easeOut', // Bounce effect on landing
                                onComplete: () => {
                                    // --- LANDING ACTIONS ---
                                    console.log("Tax monster landed at final position.");
                                    // Ensure final position and state precisely
                                    this.taxMonster.setPosition(monsterStopX, originalMonsterY);
                                    this.taxMonster.body.reset(monsterStopX, originalMonsterY);
                                    this.taxMonster.setVelocity(0, 0); // Stop any residual velocity
                                    this.taxMonster.setImmovable(true); // Make it a solid wall NOW

                                    this.cameras.main.shake(300, 0.015); // Shake screen

                                    // --- Spawn and Drop Question Mark Block (Existing Logic) ---
                                    if (!this.questionMarkBlock) { // Create only once
                                        const targetTileIndex = 68;
                                        const blockX = (targetTileIndex * this.groundTileSize) + (this.groundTileSize / 2);
                                        const baseBlockY = this.physics.world.bounds.height - this.groundTileSize * 3.5;
                                        
                                        let tempBlock = this.add.sprite(0, 0, 'question-block_atlas', 'QB1.png');
                                        const tempScaleFactor = this.groundTileSize / tempBlock.height;
                                        const scaledBlockHeight = tempBlock.height * tempScaleFactor;
                                        tempBlock.destroy();
                                        const finalBlockY = baseBlockY - (scaledBlockHeight * 1.5);
                                        const initialBlockY = finalBlockY - 500;

                                        this.questionMarkBlock = this.physics.add.sprite(blockX, initialBlockY, 'question-block_atlas', 'QB1.png');
                                        const scaleFactor = this.groundTileSize / this.questionMarkBlock.height;
                                        this.questionMarkBlock.setScale(scaleFactor);

                                        this.physics.world.enable(this.questionMarkBlock);
                                        this.questionMarkBlock.body.setSize(this.questionMarkBlock.displayWidth, this.questionMarkBlock.displayHeight);
                                        this.questionMarkBlock.body.setAllowGravity(false);
                                        this.questionMarkBlock.setImmovable(true);
                                        this.questionMarkBlock.setOrigin(0.5);
                                        this.questionMarkBlock.setDepth(this.player.depth + 1);

                                        console.log(`Spawning question mark block at Y=${initialBlockY.toFixed(1)} and tweening down to Y=${finalBlockY.toFixed(1)}.`);
                                        
                                        // --- Play Question Block Fall Sound ---
                                        const soundManager = this.registry.get('soundManager');
                                        if (soundManager) {
                                            soundManager.playSound('questionBlockFallSound', { volume: 0.2 });
                                        } else {
                                            console.warn('SceneOne: SoundManager not found. Cannot play question block fall sound.');
                                        }
                                        // --- End Sound ---

                                        this.tweens.add({
                                            targets: this.questionMarkBlock,
                                            y: finalBlockY,
                                            duration: 600,
                                            ease: 'Bounce.easeOut',
                                            onComplete: () => {
                                                this.questionMarkBlock.body.reset(this.questionMarkBlock.x, this.questionMarkBlock.y);
                                                this.questionMarkBlock.play('question-block_spin');
                                                console.log("Question mark block landed and spinning at:", blockX.toFixed(1), finalBlockY.toFixed(1));
                                            }
                                        });
                                    }
                                    // --- End Block Spawn/Drop ---
                                } // End Landing onComplete
                            }); // End Down Tween
                        } // End Up onComplete
                    }); // End Up Tween
                    // --- End Monster Jump Sequence ---
                }
            } // End outer if (this.taxMonster)
            // --- End Tax Monster Logic ---

            // --- Question Mark Block Hit Check ---
            if (this.questionMarkBlock && !this.isQuestionMarkBlockHit) {
                // Check for overlap between player and block
                // We need to be more specific than simple overlap: hit from below while jumping
                const playerBounds = this.player.getBounds();
                const blockBounds = this.questionMarkBlock.getBounds();
                const isMovingUp = this.player.body.velocity.y < 0;
                const tolerance = 10; // Pixels overlap tolerance

                // Check if player's top is hitting the block's bottom & player is moving up
                const hitBottom = Phaser.Geom.Intersects.RectangleToRectangle(playerBounds, blockBounds) &&
                                  isMovingUp &&
                                  playerBounds.top < blockBounds.bottom &&
                                  playerBounds.bottom > blockBounds.bottom; // Ensure player isn't fully above
                                  // playerBounds.centerX > blockBounds.left && // Optional stricter horizontal check
                                  // playerBounds.centerX < blockBounds.right;

                if (hitBottom) {
                    console.log("Question Mark Block Hit from Below!");
                    this.isQuestionMarkBlockHit = true; // Set flag to prevent multiple triggers

                    // --- Play Question Block Hit Sound ---
                    const soundManager = this.registry.get('soundManager');
                    if (soundManager) {
                        soundManager.playSound('questionBlockHitSound', { volume: 0.2 });
                    } else {
                        console.warn('SceneOne: SoundManager not found. Cannot play question block hit sound.');
                    }
                    // --- End Sound ---

                    // Stop the spinning animation and set to the 'hit' frame
                    this.questionMarkBlock.anims.stop();
                    this.questionMarkBlock.setFrame('QB4.png'); 

                    // Disable player controls
                    this.player.disableMovement();

                    // Make the block bounce slightly
                    this.tweens.add({
                        targets: this.questionMarkBlock,
                        y: this.questionMarkBlock.y - 8,
                        duration: 80,
                        ease: 'Power1',
                        yoyo: true,
                        onComplete: () => {
                            // --- Spawn Aave Loan Object AFTER block bounce --- 
                            const loanX = this.questionMarkBlock.x;
                            const loanStartY = this.questionMarkBlock.y;
                            this.aaveLoanObject = this.add.sprite(loanX, loanStartY, 'aave-loan-scroll_atlas', 'aave-loan-scroll.png');
                            
                            // Scale the loan object (original is 1019x1019)
                            const desiredLoanHeight = 150; // pixels
                            const scaleFactorLoan = desiredLoanHeight / this.aaveLoanObject.height;
                            this.aaveLoanObject.setScale(scaleFactorLoan);

                            this.aaveLoanObject.setOrigin(0.5, 1); // Origin at bottom-center
                            // Ensure loan is in front of the hit block
                            this.aaveLoanObject.setDepth(this.questionMarkBlock.depth + 1); // Appear in front of block
                            console.log("Spawned Aave Loan Scroll (real asset)");

                            // Pop up tween
                            this.tweens.add({
                                targets: this.aaveLoanObject,
                                y: loanStartY - 40, // Move up 40 pixels
                                duration: 200,
                                ease: 'Power1',
                                onComplete: () => {
                                    // Start hovering/following logic after pop-up
                                    console.log("Aave Loan Pop-up complete, starting hover.");

                                    // --- Play Get Aave Sound ---
                                    const soundManager = this.registry.get('soundManager');
                                    if (soundManager) {
                                        soundManager.playSound('getAaveSound', { volume: 0.2 });
                                    } else {
                                        console.warn('SceneOne: SoundManager not found. Cannot play get Aave sound.');
                                    }
                                    // --- End Sound ---

                                    // --- Display Text & Update Counters --- 
                                    const loanText = this.add.text(
                                        this.aaveLoanObject.x,
                                        this.aaveLoanObject.y - 30, // Position above the loan object
                                        'You took out an Aave loan!',
                                        {
                                            fontSize: '20px',
                                            fill: '#ffffff',
                                            backgroundColor: 'rgba(0,0,0,0.7)',
                                            padding: { x: 8, y: 4 },
                                            align: 'center'
                                        }
                                    ).setOrigin(0.5);
                                    loanText.setDepth(100); // Set a high depth to ensure it's above monster, player, etc.

                                    // Update counters
                                    this.counterValue.value += 400000;
                                    this.ethCounterValue.value = Math.max(0, this.ethCounterValue.value - 450); // Prevent negative ETH
                                    this.aaveCounterValue.value = 450; // Set Aave value

                                    // Update display text
                                    this.counterText.setText(`$: ${Math.floor(this.counterValue.value).toLocaleString()}`);
                                    this.ethCounterText.setText(`ETH: ${Math.floor(this.ethCounterValue.value)}`);
                                    this.aaveCounterText.setText(`Aave: ${this.aaveCounterValue.value}`); // Update Aave text
                                    this.aaveCounterText.setVisible(true); // Show Aave counter

                                    // Remove text after a delay
                                    this.time.delayedCall(2000, () => {
                                        loanText.destroy();
                                    }, [], this);

                                    // Re-enable player movement
                                    this.player.enableMovement();
                                    
                                    // --- NEW: Set player to Aave loan holding state ---
                                    this.player.startHoldingLoan();
                                    // --- END NEW ---
                                    
                                    // We'll add the follow logic in the main update loop
                                }
                            });
                        }
                    });

                    // Player should bounce off slightly
                    this.player.setVelocityY(50);
                }
            }
            // --- End Question Mark Block Hit Check ---

            // --- Aave Loan Hover/Follow Logic ---
            if (this.aaveLoanObject && this.isQuestionMarkBlockHit) {
                const targetX = this.player.x;
                // const targetY = this.player.y - this.player.height * 0.75; // Old calculation

                // New calculation: Position bottom of scroll 20px above player's visual top
                // const desiredGapAbovePlayer = 5; // Adjust this gap as needed
                // const targetY = this.player.getBounds().top - desiredGapAbovePlayer;
                const targetY = 500; // Directly set TargetY to 300

                // Add this log to see what's happening:
                // console.log(`Player Y: ${this.player.y}, Player H: ${this.player.height}, TargetY: ${targetY}, Scroll CurrentY: ${this.aaveLoanObject.y}`);
                console.log(`Player Top: ${this.player.getBounds().top.toFixed(2)}, TargetY: ${targetY.toFixed(2)}, Scroll CurrentY: ${this.aaveLoanObject.y.toFixed(2)}`);

                // Smoothly follow the player's X position
                this.aaveLoanObject.x = Phaser.Math.Linear(this.aaveLoanObject.x, targetX, 0.1); // Adjust interpolation factor (0.1) for smoothness
                // Keep Y position fixed relative to player
                // this.aaveLoanObject.y = targetY;
                this.aaveLoanObject.y = Phaser.Math.Linear(this.aaveLoanObject.y, targetY, 0.1); // Also smooth Y
            }
            // --- End Aave Loan Hover/Follow Logic ---

            // --- Transition to SceneTwo if player goes off right edge ---
            if (this.player.x > this.physics.world.bounds.width) {
                if (!this.sceneTransitioned) { // Prevent multiple transitions
                    this.sceneTransitioned = true;
                    console.log("SceneOne: Player moved off screen right. Transitioning to InterstitialScene for SceneTwo.");
                    // Play.fun: level 1 complete bonus
                    awardPoints(100);
                    // Prepare data to pass to SceneTwo
                    const sceneTwoData = {
                        dollars: Math.floor(this.counterValue.value),
                        eth: Math.floor(this.ethCounterValue.value),
                        aave: this.aaveCounterValue.value, // Pass Aave value as well
                        hits: this.registry.get('playerHits')
                    };
                    // Transition to the Interstitial Scene first
                    this.scene.start('InterstitialScene', {
                        nextSceneKey: 'SceneTwo',
                        imageKey: 'interstitial2',
                        sceneData: sceneTwoData
                    });
                    // this.scene.start('SceneTwo', sceneTwoData); // Old direct transition
                }
            }
        }

        // --- Keep elements positioned correctly during animation ---
        if (this.gameState === 'animating') {
            // Keep funnel above player's head
            if (this.funnel) {
                this.funnel.x = this.player.x;
            }
            // Keep emitter high above funnel
            if (this.coinEmitter) {
                const targetEmitterY = this.funnel.y - 250;
                this.coinEmitter.setPosition(this.funnel.x, targetEmitterY);
            }
        }

        // --- Update Background Tile Positions for Parallax ---
        // REMOVED: Redundant code, setScrollFactor handles this for TileSprites
        /*
        if (this.bgFar) {
            this.bgFar.tilePositionX = this.cameras.main.scrollX * 0.2; // Match scrollFactor
        }
        if (this.bgMid) {
            this.bgMid.tilePositionX = this.cameras.main.scrollX * 0.5; // Match scrollFactor
        }
        */
    }
}

// Make class available (if using modules later)
// export default GameScene;
